- name: Copy Docker Compose file to the instance
  copy:
    src: ./docker-compose.yml
    dest: /home/ec2-user/docker-compose.yml
    owner: ec2-user
    group: ec2-user
    mode: '0644'

- name: Run Docker Compose
  command: docker-compose -f /home/ec2-user/docker-compose.yml up -d